// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmfrvfjfxgyztcjfqrlk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtZnJ2ZmpmeGd5enRjamZxcmxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1NjYxNjYsImV4cCI6MjA1OTE0MjE2Nn0.eTf0y0ReT5FhcLTiuQBpF-WJXCxrFzWtYoNNXl17Vpo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);